apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-ms-deployment
  labels:
    app: customer-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-ms
  template:
    metadata:
      labels:
        app: customer-ms
    spec:
      containers:
      - name: customer-ms
        image: NTTBanktesteastus2acr.azurecr.io/customer-microservice:latest
        ports:
        - containerPort: 8082
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-ms-service
spec:
  selector:
    app: customer-ms
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082